import Head from "next/head";
import GarmentUploader from "~/components/GarmentUploader";
import Garments from "~/components/Garments";
import Models from "~/components/Models";
import TryOnComponent from "~/components/TryOnComponent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen mt-24 max-w-4xl mx-auto">
        {/* <GarmentUploader /> */}
        <Garments />
        <Models />
        <TryOnComponent />
      </main>
    </>
  );
}
