import Head from "next/head";
import Garments from "~/components/Garments";
import Models from "~/components/Models";
import Navigation from "~/components/Navigation";
import TryOnComponent from "~/components/TryOnComponent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cloti</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-h-screen max-w-md mx-auto">
        <Models />
        <Garments />
        <Navigation />
      </main>
    </>
  );
}
